 import type { Metadata } from "next";
import { Inter, Poppins, Roboto, Geist } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { TRPCReactProvider } from '@/trpc/client';
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"
import { ThemeProvider } from "next-themes";
import { APP_URL } from "@/constants";
const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
 subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider 
      domain={APP_URL}
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignOutUrl={"/"} >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}  antialiased`}
      >
       <TRPCReactProvider>
        <Toaster />
        <TooltipProvider>
         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
        </TooltipProvider>
        </TRPCReactProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
