 import type { Metadata } from "next";
import { Inter, Poppins, Roboto, Geist } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { TRPCReactProvider } from '@/trpc/client';
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"
const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
 subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider afterSignOutUrl={"/"} >
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${inter.className}  antialiased`}
      >
       <TRPCReactProvider>
        <Toaster />
        <TooltipProvider>
         {children} 
        </TooltipProvider>
        </TRPCReactProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
